
WORKSPACE_PATH = 'Tensorflow\workspace'
SCRIPTS_PATH = 'Tensorflow\scripts'
APIMODEL_PATH = 'Tensorflow\models'
ANNOTATION_PATH = WORKSPACE_PATH+'\Annotations'
IMAGE_PATH = WORKSPACE_PATH+'\images'
MODEL_PATH = WORKSPACE_PATH+'\models'
PRETRAINED_MODEL_PATH = WORKSPACE_PATH+'\pre-trained-models'
CONFIG_PATH = MODEL_PATH+'\my_ssd_mobnet\pipeline.config'
CHECKPOINT_PATH = MODEL_PATH+'\my_ssd_mobnet'